### ISSUE TITLE
Handle base case of directory?

### ISSUE THREAD

**Issue by arichiardi** [weavejester/resauce#1]
Hello James, this tiny library here really saved me from the Java purgatory: I was already kind of picturing myself banging my head on the wall while trying to make sense out of Java resources and methods to fetch them when I stumbled across it.

Big thanks.

One thing I have noticed, maybe by design, is that `directory?` does not handle the case where the input url is `nil`, which can happen when chaining directly, for example in this sample (cut for brevity):

```
;; Java resources are the best, how to know if the resource path is a dir?
;; http://stackoverflow.com/questions/20105554/is-there-a-way-to-tell-if-a-classpath-resource-is-a-file-or-a-directory
(->> (str path (when-not (= \/ (last path)) "/")) 
     (.findResource classloader)
     (res/directory? r))
```

Is it something you would like to add by any chance?

**Comment by weavejester** [comment]
I think that's a good idea. A `:default` case that just returns `false` would be a sensible addition, and I'd welcome a PR to that effect.
