### ISSUE TITLE
url-dir can return strings, despite its docstring

### ISSUE THREAD

**Issue by p-himik** [weavejester/resauce#6]
The docstring for `url-dir` says:
> Return a list of URLs contained by this URL, if the protocol supports it.

But `url-dir` method for `"jar"` uses `build-url` which returns strings.

**Comment by weavejester** [comment]
Yes, the docstring could be clearer. It should read something more like:

```
"Return a list of URL strings contained by this URL, if the protocol supports it."
```

**Comment by p-himik** [comment]
But that's the thing - `url-dir` for `"file"` returns a list of URLs. So the multimethod returns different types for different schemas.

**Comment by weavejester** [comment]
Ah, you're right. In which case, we should probably standardize on URLs, and change the multimethod for "jar" to return URL instances rather than strings.

**Comment by p-himik** [comment]
I agree. Although, that would be a backward incompatible change. An opportunity to release `1.0.0`, perhaps? :)

**Comment by weavejester** [comment]
The library isn't 1.0, so it's fine to break things, particularly if they won't affect a lot of people. I think I'd rather release 0.2.0 rather than 1.0.0, and then after a while of use promote the 0.2.0 release to 1.0.0.
